# Model Inference

> This section explains the process of saving and loading models and other files related to the results of the models that we created in the previous chapter. Since there are only 10 data, handling outliers could be skipped.

In [11]:
# Importing Libraries
import pandas as pd

# Save and Load Model
import pickle
import json

In [12]:
# Load Model Files

with open('kmeans.pkl', 'rb') as file_1:
  kmeans = pickle.load(file_1)

with open('s_minmaxscaler.pkl', 'rb') as file_2:
  s_minmaxscaler = pickle.load(file_2)

with open('pca.pkl', 'rb') as file_3:
  pca = pickle.load(file_3)

## Load Data Inference

In [13]:
# Load Data Inference
df_inf = pd.read_csv('inference_Credit_Card_Customer_Segmentation.csv')
df_inf = df_inf.drop(['Unnamed: 0'],axis=1)
df_inf = df_inf.set_index('CUST_ID')
df_inf_copy = df_inf.copy()
df_inf_copy = df_inf.drop(['TENURE'],axis=1)
df_inf_copy

,BALANCE,BALANCE_FREQUENCY,PURCHASES,ONEOFF_PURCHASES,INSTALLMENTS_PURCHASES,CASH_ADVANCE,PURCHASES_FREQUENCY,ONEOFF_PURCHASES_FREQUENCY,PURCHASES_INSTALLMENTS_FREQUENCY,CASH_ADVANCE_FREQUENCY,CASH_ADVANCE_TRX,PURCHASES_TRX,CREDIT_LIMIT,PAYMENTS,MINIMUM_PAYMENTS,PRC_FULL_PAYMENT
CUST_ID,,,,,,,,,,,,,,,,
438,3355.631092,1.000000,242.88,0.00,242.88,0.000000,1.000000,0.000000,1.000000,0.000000,0.0,12.0,13500.0,6084.115091,890.639118,0.090909
442,38.916240,1.000000,358.49,0.00,358.49,188.234434,0.916667,0.000000,0.833333,0.083333,1.0,11.0,2500.0,479.607061,141.652641,0.300000
1746,3092.948987,1.000000,1132.03,1038.75,93.28,3988.939447,0.833333,0.250000,0.583333,0.666667,25.0,19.0,7000.0,889.901799,883.612427,0.000000
2952,1.533981,0.545455,141.56,0.00,141.56,0.000000,0.500000,0.000000,0.500000,0.000000,0.0,6.0,4000.0,248.103302,44.570781,1.000000
3090,1562.633343,1.000000,1330.62,1169.63,160.99,0.000000,0.500000,0.166667,0.250000,0.000000,0.0,8.0,2000.0,1020.783647,709.610053,0.000000
3746,475.826042,1.000000,950.00,950.00,0.00,0.000000,0.083333,0.083333,0.000000,0.000000,0.0,1.0,4500.0,118.530660,290.333335,0.000000
5108,751.224820,1.000000,1000.00,0.00,1000.00,0.000000,0.416667,0.000000,0.333333,0.000000,0.0,5.0,1700.0,2025.267591,319.173449,0.083333
5118,55.147722,0.875000,163.31,0.00,163.31,0.000000,0.875000,0.000000,0.750000,0.000000,0.0,7.0,1000.0,62.619008,109.580539,0.000000
5854,2932.111796,1.000000,346.32,346.32,0.00,2631.304016,0.333333,0.333333,0.000000,0.333333,10.0,9.0,6000.0,597.514300,784.577784,0.000000
8086,101.936878,1.000000,888.96,0.00,888.96,0.000000,1.000000,0.000000,1.000000,0.000000,0.0,12.0,2000.0,790.509043,179.636117,0.833333

## Feature Scaling

In [14]:
# Feature Scaling for data inference
df_inf_scaled = s_minmaxscaler.transform(df_inf_copy)
df_inf_scaled = pd.DataFrame(df_inf_scaled, columns = df_inf_copy.columns, index = df_inf_copy.index)
df_inf_scaled

,BALANCE,BALANCE_FREQUENCY,PURCHASES,ONEOFF_PURCHASES,INSTALLMENTS_PURCHASES,CASH_ADVANCE,PURCHASES_FREQUENCY,ONEOFF_PURCHASES_FREQUENCY,PURCHASES_INSTALLMENTS_FREQUENCY,CASH_ADVANCE_FREQUENCY,CASH_ADVANCE_TRX,PURCHASES_TRX,CREDIT_LIMIT,PAYMENTS,MINIMUM_PAYMENTS,PRC_FULL_PAYMENT
CUST_ID,,,,,,,,,,,,,,,,
438,0.679121,1.000000,0.088308,0.000000,0.200511,0.000000,1.000000,0.000000,1.000000,0.000000,0.0,0.292683,1.054294,1.463831,0.516731,0.218181
442,0.007876,1.000000,0.130343,0.000000,0.295953,0.068457,0.916667,0.000000,0.833333,0.183333,0.1,0.268293,0.185587,0.115393,0.082165,0.719999
1746,0.625959,1.000000,0.411592,0.716058,0.077008,1.450687,0.833333,0.300000,0.583333,1.466669,2.5,0.463415,0.540967,0.214109,0.512654,0.000000
2952,0.000310,-0.636364,0.051469,0.000000,0.116866,0.000000,0.500000,0.000000,0.500000,0.000000,0.0,0.146341,0.304047,0.059693,0.025837,2.399995
3090,0.316250,1.000000,0.483797,0.806280,0.132906,0.000000,0.500000,0.200001,0.250000,0.000000,0.0,0.195122,0.146101,0.245599,0.411697,0.000000
3746,0.096299,1.000000,0.345408,0.654879,0.000000,0.000000,0.083333,0.100000,0.000000,0.000000,0.0,0.024390,0.343534,0.028518,0.168430,0.000000
5108,0.152035,1.000000,0.363588,0.000000,0.825555,0.000000,0.416667,0.000000,0.333333,0.000000,0.0,0.121951,0.122409,0.487277,0.185163,0.199999
5118,0.011161,0.550000,0.059378,0.000000,0.134821,0.000000,0.875000,0.000000,0.750000,0.000000,0.0,0.170732,0.067127,0.015066,0.063556,0.000000
5854,0.593408,1.000000,0.125918,0.238734,0.000000,0.956946,0.333333,0.400000,0.000000,0.733333,1.0,0.219512,0.461994,0.143761,0.455194,0.000000
8086,0.020630,1.000000,0.323215,0.000000,0.733885,0.000000,1.000000,0.000000,1.000000,0.000000,0.0,0.292683,0.146101,0.190196,0.104203,1.999995

##  Model Training Inference

In [15]:
# PCA analysis
pca_inf = pca.transform(df_inf_scaled)
pca_inf

C:\Users\luay9\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\base.py:413: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(

array([[ 0.58261301,  0.3979288 , -0.43621298],
       [ 0.40012033, -0.49341333, -0.60288534],
       [-0.63699729,  2.14053573, -0.20088291],
       [ 0.23073919, -1.54881848,  0.44870195],
       [ 0.21182972, -0.03420654,  0.25291463],
       [-0.2609037 , -0.34004561,  0.38743449],
       [ 0.18634654, -0.30840827, -0.32103615],
       [ 0.13211173, -0.72468354, -0.49734082],
       [-0.80095901,  0.92268827,  0.07071711],
       [ 1.03064716, -0.75431671, -0.57947127]])

In [16]:
# Cluster inference
y_inf = kmeans.predict(pca_inf)

# Create DataFrame
y_inf = pd.DataFrame(y_inf, columns=['Customer Segmentation (Inference)'],index=df_inf_scaled.index)
y_inf

         Customer Segmentation (Inference)
CUST_ID
438                                      0
442                                      1
1746                                     2
2952                                     1
3090                                     1
3746                                     1
5108                                     1
5118                                     1
5854                                     2
8086                                     1

In [17]:
# Concatinate with Data inference
model_inf = pd.concat([df_inf, y_inf['Customer Segmentation (Inference)']], axis=1).sort_index()
model_inf

,BALANCE,BALANCE_FREQUENCY,PURCHASES,ONEOFF_PURCHASES,INSTALLMENTS_PURCHASES,CASH_ADVANCE,PURCHASES_FREQUENCY,ONEOFF_PURCHASES_FREQUENCY,PURCHASES_INSTALLMENTS_FREQUENCY,CASH_ADVANCE_FREQUENCY,CASH_ADVANCE_TRX,PURCHASES_TRX,CREDIT_LIMIT,PAYMENTS,MINIMUM_PAYMENTS,PRC_FULL_PAYMENT,TENURE,Customer Segmentation (Inference)
CUST_ID,,,,,,,,,,,,,,,,,,
438,3355.631092,1.000000,242.88,0.00,242.88,0.000000,1.000000,0.000000,1.000000,0.000000,0.0,12.0,13500.0,6084.115091,890.639118,0.090909,12.0,0
442,38.916240,1.000000,358.49,0.00,358.49,188.234434,0.916667,0.000000,0.833333,0.083333,1.0,11.0,2500.0,479.607061,141.652641,0.300000,12.0,1
1746,3092.948987,1.000000,1132.03,1038.75,93.28,3988.939447,0.833333,0.250000,0.583333,0.666667,25.0,19.0,7000.0,889.901799,883.612427,0.000000,12.0,2
2952,1.533981,0.545455,141.56,0.00,141.56,0.000000,0.500000,0.000000,0.500000,0.000000,0.0,6.0,4000.0,248.103302,44.570781,1.000000,12.0,1
3090,1562.633343,1.000000,1330.62,1169.63,160.99,0.000000,0.500000,0.166667,0.250000,0.000000,0.0,8.0,2000.0,1020.783647,709.610053,0.000000,12.0,1
3746,475.826042,1.000000,950.00,950.00,0.00,0.000000,0.083333,0.083333,0.000000,0.000000,0.0,1.0,4500.0,118.530660,290.333335,0.000000,12.0,1
5108,751.224820,1.000000,1000.00,0.00,1000.00,0.000000,0.416667,0.000000,0.333333,0.000000,0.0,5.0,1700.0,2025.267591,319.173449,0.083333,12.0,1
5118,55.147722,0.875000,163.31,0.00,163.31,0.000000,0.875000,0.000000,0.750000,0.000000,0.0,7.0,1000.0,62.619008,109.580539,0.000000,8.0,1
5854,2932.111796,1.000000,346.32,346.32,0.00,2631.304016,0.333333,0.333333,0.000000,0.333333,10.0,9.0,6000.0,597.514300,784.577784,0.000000,12.0,2
8086,101.936878,1.000000,888.96,0.00,888.96,0.000000,1.000000,0.000000,1.000000,0.000000,0.0,12.0,2000.0,790.509043,179.636117,0.833333,12.0,1

Based on the table above, we can see the Holders/Customers Segmentation from data inference shows that there are:

- 2 customers segmented as Cluster 0 (credit card holders who frequently make purchases)
- 6 customers segmented as Cluster 1 (credit card holders who don't use their credit cards very frequently to make purchases)
- 2 customers segmented as Cluster 2 (credit card holders who frequently use Cash in advance payment method when making purchases)